### ISSUE TITLE
Health must be between 0 and 20

### ISSUE THREAD

**Issue by Zilacon** [KaiKikuchi/KaisRandomTeleport#3]
Getting this error on Thermos Build 53. Any chance for a fix? Its spamming it multiple times a second.
Running this modpack: http://www.technicpack.net/modpack/apocalyptic-adventures.801085

````[19:17:13 WARN]: [KaisRandomTP] Task #30254 for KaisRandomTP v1.4 generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 20.0
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:72) ~[CraftLivingEntity.class:1.7.10-1614.53]
	at net.kaikk.mc.rtp.PlayerSafeTask.run(PlayerSafeTask.java:26) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.53]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.53]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:895) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]````

**Comment by KaiKikuchi** [comment]
You're using a very old version of the plugin.
